name: Deploy Application

on:
  push:
    branches:
      - main  # Change to 'master' if your main branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/To-Do-web/server
            git pull origin main
            npm install
            pm2 reload My-Portal-UCP || pm2 restart My-Portal-UCP